### ISSUE TITLE
Global Pitch

### ISSUE THREAD

**Issue by ndrahmani** [ManimCommunity/manim-voiceover#16]
## Description of proposed feature
Sometimes we want to configure the global pitch used in each voiceover piece 

## How can the new feature be used?
setting the pitch globally so we can avoid repeating prosody in each voiceover step

**Comment by osolmaz** [comment]
This is already added. 

https://github.com/ManimCommunity/manim-voiceover/blob/bfaa4c3cc05011af11ca6169787c1845f365dbf4/manim_voiceover/services/azure.py#L46-L51

Initialize it as: 

```py
AzureService(..., prosody={ ... }):
```
