### ISSUE TITLE
Setting transcript language in RecorderService

### ISSUE THREAD

**Issue by Gebro420** [ManimCommunity/manim-voiceover#34]
Whisper has a functionality (i.e. a flag for it) to set language. So in theory, it does not have to detect it. It can be helpful because some languages are more easily erroneously detected than others.

**Comment by osolmaz** [comment]
This is implemented by #35. You can now set it like
```py
RecorderService(..., transcription_kwargs={"language": "de"})
```
Dict items will be passed to `mode.transcribe()` as kwargs.

[See the documentation](https://voiceover.manim.community/en/stable/api.html#manim_voiceover.services.base.SpeechService) for more details.
