### ISSUE TITLE
Humanhash3 causes installation errors on Chinese locale

### ISSUE THREAD

**Issue by Tejas242** [ManimCommunity/manim-voiceover#39]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://voiceover.manim.community/en/latest/installation.html).

## Description of error

When I try to install manim-voiceover library with "pip install --upgrade "manim-voiceover[azure,gtts]" It produces error while installing the humanhash3. The output log is attached below.

## Installation logs

Collecting manim-voiceover[azure,gtts]
  Using cached manim_voiceover-0.3.0-py3-none-any.whl (37 kB)
Requirement already satisfied: manim in c:\tools\manim\lib\site-packages (from manim-voiceover[azure,gtts]) (0.17.2)
Collecting humanhash3<0.0.7,>=0.0.6
  Using cached humanhash3-0.0.6.tar.gz (5.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-dq4c4am1\humanhash3_9cdb2df319f347f9a53bc7df772b27db\setup.py", line 7, in <module>
          long_description = f.read()
      UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1081: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## System specifications

<details><summary>System Details</summary>

- OS (Windows 11 22H2):
- RAM: 8GB
- Python version : 3.10.8 
</details>

**Comment by osolmaz** [comment]
> GPT-4: 
> The error you're encountering originates from the installation of humanhash3 package, and it is due to a Unicode decoding issue. The error occurs when Python attempts to read a file using the 'cp950' codec and encounters a byte sequence it cannot decode.
> 
> In this case, the sequence is '0xe2' at position 1081, which the 'cp950' codec can't decode.
> 
> The 'cp950' codec is a code page used by Microsoft Windows to write traditional Chinese characters. If you are not using a Chinese version of Windows or don't need traditional Chinese characters, this is probably not the codec you want Python to use by default.

It seems like we need a solution other than humanhash for making filenames readable. I will look deeper into this soon.
