### ISSUE TITLE
Bookmarks do not work with Coqui speech service

### ISSUE THREAD

**Issue by tn3wman** [ManimCommunity/manim-voiceover#42]
## Description of bug / unexpected behavior

Tried to run the bookmark example with Coqui. The animations don't wait for bookmarks correctly.

## Expected behavior

Expected to play the same as using Azure speech service.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from TTS.api import TTS
scene.set_speech_service(CoquiService(model_name=TTS.list_models()[17], speaker_idx=TTS(TTS.list_models()[17]).speakers[47]))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- Windows 10
- Python version 3.9.13:
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100```
</details>

## Additional comments
<!-- Add further context that you think might be relevant for this issue here. -->

**Comment by tn3wman** [comment]
It seems to be an issue with the model or speaker I used. Simply using  

```self.set_speech_service(CoquiService())```

seems to work ok.

**Comment by osolmaz** [comment]
There have also been simplifications to CoquiService initialization in v0.3.1. Closing this now, feel free to open a new one if you encounter any issues.
