### ISSUE TITLE
wait_until_bookmark (Word boundaries for any audio)

### ISSUE THREAD

**Issue by andrewpenland** [ManimCommunity/manim-voiceover#7]
When working with the wait_until_bookmark function with GTTSService, the following error occurs in the 'time_until_bookmark' function in the "manim_voiceover/__init__.py" file. 

AttributeError: 'VoiceoverTracker' object has no attribute 'bookmark_times'

**Comment by osolmaz** [comment]
Google Translate API doesn't return word boundaries (timings), so it's not possible to use bookmarks with GTTS yet. I'd recommend using AzureService.

TODO: Raise an exception when bookmarks are used with a service that doesn't support bookmarks

**Comment by osolmaz** [comment]
I'm keeping this open until we implement STT & word-boundary detection for any audio, fyi

**Comment by osolmaz** [comment]
This has been implemented in version 0.2.0.
